W4D2/Cats99/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    member do
      get 'approve'
      get 'deny'
    end
  end
end

W4D2/Cats99/app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = [
    'black', 'orange','calico', 'tabby', 'white',
    'brown', 'purple', 'rose-gold'
  ]
  validates :name, presence: true
  validates :color, inclusion: { in: COLORS, message: 'not a valid cat-color' }
  validates :sex, inclusion: { in: ['M','F'], message: 'Does not adhere to gender binary' }

  has_many :cat_rental_requests,
    dependent: :destroy,
    class_name: :CatRentalRequest,
    primary_key: :id,
    foreign_key: :cat_id


  def self.colors
    COLORS
  end


end

W4D2/Cats99/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :status, inclusion: { in: ['PENDING','APPROVED', 'DENIED'], message: 'Not a recognized status' }
  validates :status, :start_date, :end_date, :cat_id, presence: true
  validate :overlapping_approved_requests

  belongs_to :cat,
    class_name: :Cat,
    primary_key: :id,
    foreign_key: :cat_id



  def overlapping_requests
    Cat.find(cat_id).cat_rental_requests.where.not("'#{end_date}' < start_date OR '#{start_date}' > end_date").where.not("#{id} = id")
  end

  def overlapping_approved_requests
    not_denied_rental_reqs = Cat.find(cat_id).cat_rental_requests.order(:start_date).where("status = 'APPROVED'")
    not_denied_rental_reqs.each do |req|
      if start_date <= req.start_date
        if end_date >= req.start_date
          return false
        end

      end
      if start_date >= req.start_date
        if start_date <= req.end_date
          return false
        end
      end
    end
    true
  end

  def approve!
    ActiveRecord::Base.transaction do
      CatRentalRequest.find(id).update(:status => "APPROVED")
      CatRentalRequest.find(id).overlapping_requests.each do |req|
        req.deny!
      end
    end
  end

  def deny!
    CatRentalRequest.find(id).update(:status => "DENIED")
  end

  def pending?
    return true if CatRentalRequest.find(id).status == "PENDING"
    false 
  end
end

W4D2/Cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

W4D2/Cats99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    render :new
  end

  def create
    req =  CatRentalRequest.new(cat_rental_request_params)
    if req.save
      redirect_to cat_url(cat_rental_request_params[:cat_id])
    else
      render json: req.errors.full_messages, status: 422
    end
  end

  def approve
    cid = CatRentalRequest.find(params[:id]).cat_id
    cat = Cat.find(cid)
    CatRentalRequest.find(params[:id]).approve!
    redirect_to cat_url(cat)
  end

  def deny
    cid = CatRentalRequest.find(params[:id]).cat_id
    cat = Cat.find(cid)
    CatRentalRequest.find(params[:id]).deny!
    redirect_to cat_url(cat)
  end


  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id, :status)
  end
end

W4D2/Cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    cat = Cat.new(cat_params)

    if cat.save
      redirect_to cats_url
    else
      render(:json => cat.errors.full_messages, :status => :unprocessable_entity)
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def update
    cat = Cat.find(params[:id])

    if cat.update(cat_params)
      redirect_to cat_url
    else
      render(:json => cat.errors.full_messages, :status => :unprocessable_entity)
    end
  end

  def destroy
    cat = Cat.find(params[:id])

    if cat.destroy
      redirect_to cats_url
    else
      render(:json => cat.errors.full_messages, :status => :unprocessable_entity)
    end
  end

  private

  def cat_params
    params.require(:cat).permit( :birth_date, :color, :name, :sex, :description )
  end
end

W4D2/Cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

W4D2/Cats99/app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% method_verb = cat.persisted? ? 'PATCH' : 'POST' %>
<% flavor_text = cat.persisted? ? 'Edit a cat' : 'Create a cat' %>

<form action=" <%= action_url %>" method="post">
  <input type = 'hidden' name = '_method' value = '<%= method_verb %>'></input>
  <h1><%= flavor_text %></h1>
  <table>
    <tr>
      <td>Name</td>
      <td>
        <input type="text" name="cat[name]" value = "<%= cat.name %>"></input>
      </td>
    </tr>

    <tr>
      <td>Birthday</td>
      <td>
        <input type="date" name="cat[birth_date]" value = "<%= cat.birth_date %>"></input>
      </td>
    </tr>

    <tr>
      <td>Color</td>
      <td>
        <select name = "cat[color]"  value = "<%= cat.color %>">
          <option value= ""> </option>

          <% Cat.colors.each do |color| %>
          <option value= "<%= color %>"
            <%= color == cat.color ? "selected = 'selected'" : ""%>
            > <%=color %> </option>
          <% end %>
        </select>
      </td>
    </tr>

    <tr>
      <td>Sex</td>
      <td>
        <input type="radio" name="cat[sex]", value = 'M'
        <%= cat.sex == "M" ? "checked" : "" %>
        >M</input>
        <input type="radio" name="cat[sex]", value = 'F'
        <%= cat.sex == "F" ? "checked" : "" %>
        >F</input>

      </td>
    </tr>

    <tr>
      <td>Description</td>
      <td>
        <textarea name="cat[description]" ><%= cat.description %></textarea></input>
      </td>
    </tr>

    <tr>
      <td>
        <input type="submit" value="Submit">
      </td>
    </tr>
  </table>

</form>

W4D2/Cats99/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat %>

W4D2/Cats99/app/views/cats/index.html.erb
<ul>
  <% @cats.each do |cat| %>
    <li><a href=" <%=cat_url(cat) %> " > <%= cat.name %></a></li>
  <% end %>
</ul>

<a href=" <%= new_cat_url %> ">New cat</a>

W4D2/Cats99/app/views/cats/new.html.erb
<%= render 'form', cat: @cat %>

W4D2/Cats99/app/views/cats/show.html.erb
<table>
  <tr>
    <td>
      Name:
    </td>
    <td>
      <%= @cat.name %>
    </td>
  </tr>
  <tr>
    <td>
      Birthday:
    </td>
    <td>
      <%= @cat.birth_date %>
    </td>
  </tr>
  <tr>
    <td>
      Color:
    </td>
    <td>
      <%= @cat.color %>
    </td>
  </tr>
  <tr>
    <td>
      Sex:
    </td>
    <td>
      <%= @cat.sex %>
    </td>
  </tr>
  <tr>
    <td>
      Description:
    </td>
    <td>
      <%= @cat.description %>
    </td>
  </tr>
</table>

<form action=" <%= cat_url(@cat) %>" method="post">
  <input type = 'hidden' name = '_method' value = 'DELETE'></input>
  <input type="submit" value="Kill cat">
</form>
<a href = "<%= edit_cat_url(@cat) %>"> Edit Cat </a>
<br>

<a href=" <%=cats_url %> " > Back  </a>
<br><br>
<aside> Current rentals: </aside>
<a href = "<%= new_cat_rental_request_url %>">Request this cat!</a>
<table>
<% @cat.cat_rental_requests.order(:start_date).each do |req| %>
<tr> <td><%= req.start_date %></td>
  <td> <%= req.end_date %> </td>
  <td> <%= req.status %> </td>
  <% if req.pending? %>
    <td>
      <form action=" <%= approve_cat_rental_request_url(req.id) %>" method="GET"><input type="submit" value="Approve"></form>
    </td>
    <td>
      <form action=" <%= deny_cat_rental_request_url(req.id) %>" method="GET"><input type="submit" value="Deny"></form>
    </td>

    <% end %>
</tr>
<% end %>
</table>