W4D5/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resource :posts, only: [:new]
  end

  resources :posts, except: [:new, :index] do
    resources :comments, only: [:new]
    resources :votes, only: [:create]
  end

  resources :comments, only: [:create, :show] do
    resources :votes, only: [:create]
  end



  root :to => 'subs#index'
end

W4D5/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :subs, :author, presence: true
  validate :has_one_sub

  belongs_to :author,
    class_name: :User,
    foreign_key: :author_id

  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments

  has_many :votes, as: :votable

  def has_one_sub
    if self.subs.empty?
      self.errors[:subs] << "Need at least one sub"
    end
  end

  def comments_by_parent_id
    comment_map = Hash.new { |h,k| h[k] = [] }
    comments.includes(:user).map do |comment|
      comment_map[comment.parent_comment_id] << comment
    end
    comment_map
  end

  def score
    votes.select("SUM(value)").pluck("SUM(value)")
  end

end

W4D5/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_if_author, only: [:edit, :update, :destroy]
  before_action :require_logged_in

  def new
    @subs = Sub.all
    @post = Post.new
    render :new
  end

  def show
    @post = Post.find(params[:id])
    @post.comments.includes(:content, :parent_comment_id)
    @all_comments = @post.comments_by_parent_id
    render :show
  end

  def create
    post = Post.new(post_params)
    post.author = current_user
    if post.save
      redirect_to post_url(post)
    else
      flash[:errors] = post.errors.full_messages
      redirect_to sub_url(post.sub)
    end
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
    render :edit
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_url(post)
    else
      flash[:errors] = post.errors.full_messages
      redirect_to post_url(post)
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to sub_url(post.subs.last)
  end

  private

  def check_if_author
    unless current_user == Post.find(params[:id]).author
      flash[:errors] = "You must be the author, "
      redirect_to post_url(params[:id])
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

W4D5/app/helpers/posts_helper.rb
module PostsHelper
end

W4D5/app/views/posts/_comment.html.erb
<ul>
  <% all_comments[comment.id].each do |child| %>
    <li> <a href="<%= comment_url(child) %>">"<%= child.content %>"</a>
      <br> <%= child.user.username %>, <%= time_ago_in_words(child.created_at) %> ago
    </li>
        <%= render "comment", comment: child, all_comments: all_comments %>
  <% end %>
</ul>

W4D5/app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% action_verb = post.persisted? ? "patch" : "post" %>
<% flavor_text = post.persisted? ? "Edit post" : "Create post" %>

<h1><%= flavor_text %></h1>

<br><br>
<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= action_verb %>">

  <label for="title">Title</label>
  <input type="text" name="post[title]" value="<%= post.title %>" id="title">
  <br><br>
  <label for="url">URL</label>
  <input type="text" name="post[url]" value="<%= post.url %>" id="url">
  <br><br>

  <label for="content">Content</label>
  <br>
  <textarea name="post[content]" rows="8" cols="40"><%= post.content %></textarea>
  <br>

  <% subs.each_with_index do |sub, i| %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"= id ="<%= i %>" <%= 'checked' if post.sub_ids.include?(sub.id) %> >
    <label for="<%= i %>"><%= sub.title %></label>
    <br>
  <% end %>
  <input type="hidden" name="post[sub_ids][]" value="">
  <input type="submit" value="<%= flavor_text %>">
</form>

W4D5/app/views/posts/edit.html.erb
<%= render "form", subs: @subs, post: @post %>

W4D5/app/views/posts/new.html.erb
<%= render "form", subs: @subs, post: @post %>

W4D5/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br><br>
<h2>Content</h2>
<p>
  <%= @post.content %>
</p>
<form action="<%= post_votes_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="vote[votable_id]" value="<%= @post.id %>">
  <input type="hidden" name="vote[votable_type]" value="<%= @post.class %>">
  <input type="hidden" name="vote[value]" value= 1>
  <input type="submit" value="👍">
</form>
<form action="<%= post_votes_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="vote[votable_id]" value="<%= @post.id %>">
  <input type="hidden" name="vote[votable_type]" value="<%= @post.class %>">
  <input type="hidden" name="vote[value]" value= -1>
  <input type="submit" value="👎">
</form>
<% if current_user == @post.author %>
<a href="<%= edit_post_url(@post) %>">Edit this post</a>
<form action=" <%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <%= auth_token %>
  <input type="submit" value="Delete this post!">
</form>
<% end %>

<br>
<br>
<h2>Comments:</h2>
<ul>

<% @all_comments[nil].each do |child| %>
    <li><a href="<%= comment_url(child) %>">"<%= child.content %>"</a>
      <br> <%= child.user.username %>, <%= time_ago_in_words(child.created_at) %> ago
    </li>
    <%= render "comment", comment: child, all_comments: @all_comments %>
    <br><br>
<% end %>



</ul>
<a href=" <%= new_post_comment_url(@post) %>">New comment!</a>