W4D4/MusicApp/config/routes.rb
Rails.application.routes.draw do
  root to: "bands#index"
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, only: [:create, :update, :destroy, :edit, :show] do
    resources :tracks, only: :new
  end

  # resources :albums, only: [:create, :update, :destroy, :edit, :show]
  resources :tracks, only: [:create, :update, :destroy, :edit, :show]

  resources :notes, only: [:create, :update, :destroy]
end

W4D4/MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  album_name :string           not null
#  band_id    :integer          not null
#  type_album :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  ALBUM_TYPES = %w(live studio)
  validates :album_name, :band_id, :type_album, presence: true
  validates :type_album, inclusion: { in: ALBUM_TYPES }

  belongs_to(
    :band,
    class_name: :Band,
    primary_key: :id,
    foreign_key: :band_id
  )

  has_many(
    :tracks,
    dependent: :destroy,
    class_name: :Track,
    primary_key: :id,
    foreign_key: :album_id
  )
end

W4D4/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    render :new
  end


  def show
    @album = Album.find(params[:id])
    render :show
  end

  def create
    album = Album.new(album_params)
    puts album
    if album.save
      redirect_to album_url(album)
    else
      redirect_to band_url(album.band_id)
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    album = Album.find(params[:id])
    if album.update(album_params)
      redirect_to album_url(album)
    else
      flash[:errors] = album.errors.full_messages
      redirect_to album_url(album)
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to band_url(album.band_id)
  end


  private

  def album_params
    params.require(:album).permit(:album_name, :band_id, :type_album)
  end
end

W4D4/MusicApp/app/views/albums/edit.html.erb
<h1>Edit this album</h1>
<form action= '<%= album_url(@album) %>' method="post">
  <input type="hidden" name="_method" value="PATCH">
  <label>Album name
    <input type="textarea" name="album[album_name]" value=" <%= @album.album_name %>">
  </label>

  <br>
  <label>Band Name
  <select name="album[band_id]">
    <option value=""></option>
    <% Band.all.each do |band| %>
    <option value="<%= band.id %>" <%= @album.band_id == band.id ? 'selected' : '' %>><%= band.name %></option>
    <% end %>
  </select>
  </label>
  <br>

  <% Album::ALBUM_TYPES.each do |type| %>
  <input type="radio" name="album[type_album]" value="<%= type %>" <%= @album.type_album == type ? 'checked' : '' %>><%= type %>
  <% end %>

  <br>
  <input type="submit" name="name" value="Save">
</form>

W4D4/MusicApp/app/views/albums/new.html.erb
<h1>Add an album</h1>

<form action= '<%= albums_url %>' method="post">
  <label>Album name
    <input type="textarea" name="album[album_name]" value="">
  </label>
  <br>

  <input type="hidden" name="album[band_id]" value="<%= params[:band_id] %>">

  <% Album::ALBUM_TYPES.each do |type| %>
  <input type="radio" name="album[type_album]" value="<%= type %>"><%= type %>
  <% end %>

  <br>
  <input type="submit" name="name" value="Save">
</form>

W4D4/MusicApp/app/views/albums/show.html.erb
<a href="<%= bands_url %>">Home</a> > <a href="<%= band_url(@album.band) %>"><%= @album.band.name %></a> > <%= @album.album_name %>


<h2>Tracks for <%= @album.band.name %>'s <%= @album.type_album %> album <%= @album.album_name %></h2>

<ul>
  <% @album.tracks.each do |track| %>
  <li><a href="<%= track_url(track) %>"><%= track.track_name %></a></li>
  <% end %>
</ul>

<form action="<%= new_album_track_url(@album) %>" method="GET">
  <input type="submit" name="name" value="🎶 ADD A TRACK">
</form>
<form action="<%= edit_album_url %>" method="GET">
  <input type="submit" name="name" value="👨‍👨‍👦 EDIT THIS ALBUM">
</form>
<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" name="name" value="🔥 DELETE THIS ALBUM">
</form>

<br>