W4D4/MusicApp/config/routes.rb
Rails.application.routes.draw do
  root to: "bands#index"
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, only: [:create, :update, :destroy, :edit, :show] do
    resources :tracks, only: :new
  end

  # resources :albums, only: [:create, :update, :destroy, :edit, :show]
  resources :tracks, only: [:create, :update, :destroy, :edit, :show]

  resources :notes, only: [:create, :update, :destroy]
end

W4D4/MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many(
    :albums,
    dependent: :destroy,
    class_name: :Album,
    primary_key: :id,
    foreign_key: :band_id
  )

  has_many(
    :tracks,
    through: :albums,
    source: :tracks
  )
end

W4D4/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    if logged_in?
      @bands = Band.all
      render :index
    else
      flash[:errors] = "Please log in to continue"
      redirect_to new_session_url
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    band = Band.new(band_params)
    if band.save
      redirect_to band_url(band)
    else
      flash[:errors] = band.errors.full_messages
      redirect_to bands_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    band = Band.find(params[:id])
    if band.update(band_params)
      redirect_to band_url(band)
    else
      flash[:errors] = band.errors.full_messages
      redirect_to band_url(band)
    end
  end

  def destroy
    Band.find(params[:id]).destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W4D4/MusicApp/app/views/bands/edit.html.erb
<h1>Edit a band</h1>
<form action= '<%= band_url(@band) %>' method="post">
  <input type="hidden" name="_method" value="PATCH">
  <label>Band Name
  <input type="textarea" name="band[name]" value="<%= @band.name %>">
  </label>
  <br>
  <input type="submit" name="name" value="Save">
</form>

W4D4/MusicApp/app/views/bands/index.html.erb
Home >
<br>
<h2>🔥 🔥 🔥 THESE ARE THE BEST BANDS 🔥 🔥 🔥 </h2>

<ul>
  <% @bands.each do |band| %>
  <li><a href="<%= band_url(band) %>"><%= band.name %></a>
  <% end %>
</ul>


<form action="<%= new_band_url %>" method="GET">
  <input type="submit" name="name" value="ADD A BAND">
</form>

W4D4/MusicApp/app/views/bands/new.html.erb
<h1>Add a band</h1>
<form action= '<%= bands_url %>' method="post">
  <label>Band Name
  <input type="textarea" name="band[name]" value="">
  </label>
  <br>
  <input type="submit" name="name" value="Save">
</form>

W4D4/MusicApp/app/views/bands/show.html.erb
<a href="<%= bands_url %>">Home</a> >  <%= @band.name %>
<h1><%= @band.name %>'s albums</h1>

<ul>
  <% @band.albums.each do |album| %>
  <li><a href="<%= album_url(album) %>"><%= album.album_name %></a></li>
  <% end %>
</ul>
<form action="<%= new_band_album_url(band_id: @band.id) %>" method="GET">
  <input type="submit" name="name" value="🎺 ADD AN ALBUM">
</form>
<form action="<%= edit_band_url %>" method="GET">
  <input type="submit" name="name" value="😅 EDIT BAND INFO">
</form>
<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" name="name" value="🙅🏻‍♂️ DELETE THIS BAND">
</form>

<br>